# Generated by Django 5.2.5 on 2025-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0003_alter_client_owner_alter_mailing_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
