# Generated by Django 5.2.5 on 2025-09-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0004_mailing_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [("can_view_all", "Can view all records for managers")]
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_view_all", "Can view all records for managers")]
            },
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "permissions": [("can_view_all", "Can view all records for managers")]
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_all", "Can view all records for managers")]
            },
        ),
    ]
