# Generated by Django 5.2.5 on 2025-09-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0005_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all", "Can view all records for managers"),
                    ("can_send_mailing", "Can send mailing"),
                ]
            },
        ),
    ]
